Repository taktik/icure-backend, pull requests merged in 2022-02, with the labels that each got.

#331 Usage of fix method when creating a batch of patient
  src/main/kotlin/org/taktik/icure/asynclogic/PatientLogic.kt
  src/main/kotlin/org/taktik/icure/asynclogic/impl/PatientLogicImpl.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/PatientController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/PatientController.kt
Labels: bug

#332 20220202-matchHEBy
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/HealthElementController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/HealthElementController.kt
Labels: enhancement

#334 20220202-matchHealthcarePartiesBy
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/HealthcarePartyController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/HealthcarePartyController.kt
Labels: enhancement

#333 20220202-filterHcpBy
  src/main/kotlin/org/taktik/icure/asyncdao/HealthcarePartyDAO.kt
  src/main/kotlin/org/taktik/icure/asyncdao/impl/HealthcarePartyDAOImpl.kt
  src/main/kotlin/org/taktik/icure/asynclogic/HealthcarePartyLogic.kt
  src/main/kotlin/org/taktik/icure/asynclogic/impl/HealthcarePartyLogicImpl.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/HealthcarePartyController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/HealthcarePartyController.kt
Labels: enhancement

#339 Create Device API
  src/main/kotlin/org/taktik/icure/asynclogic/impl/DeviceLogicImpl.kt
Labels: enhancement

#336 20220202-matchCodesBy
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/CodeController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/CodeController.kt
Labels: enhancement

#338 20220202-addDevices
  src/main/kotlin/org/taktik/icure/asynclogic/impl/DeviceLogicImpl.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/DeviceController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/DeviceController.kt
Labels: enhancement

#340 20220202-getDevice
  src/main/kotlin/org/taktik/icure/asyncdao/DeviceDAO.kt
  src/main/kotlin/org/taktik/icure/asyncdao/impl/DeviceDAOImpl.kt
  src/main/kotlin/org/taktik/icure/asynclogic/impl/DeviceLogicImpl.kt
Labels: enhancement

#341 20220202-getDevices
  src/main/kotlin/org/taktik/icure/asyncdao/impl/DeviceDAOImpl.kt
  src/main/kotlin/org/taktik/icure/asynclogic/impl/DeviceLogicImpl.kt
Labels: enhancement

#343 20220202-deleteDevices
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/DeviceController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/DeviceController.kt
Labels: enhancement

#344 20220202-updateDevices
  src/main/kotlin/org/taktik/icure/asynclogic/impl/DeviceLogicImpl.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/DeviceController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/DeviceController.kt
Labels: enhancement

#345 20220202-updateDevice
  src/main/kotlin/org/taktik/icure/asynclogic/impl/DeviceLogicImpl.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/DeviceController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/DeviceController.kt
Labels: enhancement

#348 Fixed filterHealthElementsBy
  src/main/kotlin/org/taktik/icure/asyncdao/HealthElementDAO.kt
  src/main/kotlin/org/taktik/icure/asyncdao/impl/HealthElementDAOImpl.kt
  src/main/kotlin/org/taktik/icure/asynclogic/HealthElementLogic.kt
  src/main/kotlin/org/taktik/icure/asynclogic/impl/HealthElementLogicImpl.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/HealthElementController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/HealthElementController.kt
Labels: enhancement, invalid
